feat: poc plugin for bundle locales on the fly
ripe-tech/ripe-commons-pluginus pull request #281
Opened 2022-02-01 17:45 UTC by 3rdvision

| - | - |
| --- | --- |
| Issue | AAAAAAAAA |
| Dependencies | BBBBBBBB |
| Decisions | CCCCCCCC |
| Animated GIF | DDDDDDDD |

2022-02-18 16:28 UTC, hugo-gomes reviewed
@3rdvision what's the status of this?

2022-02-18 16:32 UTC, 3rdvision commented
> @3rdvision what's the status of this?

After a meeting with @BeeMargarida and @joamag this is now awaiting an implementation to do lazy loading.
My bad, I should have updated with a comment.
Assigning to me until it's done.

2022-02-18 16:40 UTC, hugo-gomes reviewed
@3rdvision thanks! no problem :)

2022-03-14 12:07 UTC, joamag requested changes

2022-03-14 12:07 UTC, joamag commented on js/util/locale-bundle-loader.js
> +            const ripeReadyInterval = setInterval(async () => {
avoid busy waiting and use a promise to wait for an event triggered when ripe provider is ready

2022-03-14 12:07 UTC, joamag commented on js/util/locale-bundle-loader.js
> +        if (this.loadedBundles.includes(locale)) return;
use the ripe-sdk `initBundles`

2022-08-01 14:59 UTC, merged