#978: Initials images minimum height and undefined width/height support
ripe-tech/ripe-commons-pluginus pull request #291
Opened 2022-03-08 14:46 UTC by BeeMargarida

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/978 |
| Dependencies | -- |
| Decisions | - Added `minimumHeight` to `initials-images` so that it can be controlled instead of the default `600` - required for showing images bigger than 600px, which we want in the configurator container in white, while maitaining backward compatibility with existing plugins that make use of this, like emilio_pucci <br>- Support for undefined width and height for initials image's SDK `bindImage` - required since we want the resize of the image to be made by compose to maintain the correct aspect ratio. |
| Animated GIF | ![personalization-only-dummy](https://user-images.githubusercontent.com/25725586/157260535-2e448d4a-310f-4b1e-bb50-a5620bdc1ec0.gif)![personalization-only-ysl](https://user-images.githubusercontent.com/25725586/157260573-68fc23c5-d98d-40cf-95b5-6650cc8f7f7a.gif)![personalization-only-mobile](https://user-images.githubusercontent.com/25725586/157260580-c7e45116-b408-4d51-9422-25d6c27bf68d.gif)|

2022-03-08 15:01 UTC, 3rdvision approved these changes

2022-03-09 11:21 UTC, joamag requested changes

2022-03-09 11:21 UTC, joamag commented on vue/components/forms/personalization-form/initials-images.vue
> +        minHeight: {
move this up to the same place where the height is present

2022-03-09 11:36 UTC, joamag approved these changes

2022-03-09 11:36 UTC, merged